# Generated by Django 3.2.16 on 2023-01-27 04:41
from json import load

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    with open("mainapp/fixtures/001_news.json") as f:
        news_fixture = load(f)
    News = apps.get_model("mainapp", "News")
    # Create model's objects
    for item in news_fixture:
        if not News.objects.filter(
            title=item.get("title"), preambule=item.get("preambule"), body=item.get("body")
        ).exists():
            if item.get("title") and item.get("preambule") and item.get("body"):
                News.objects.create(title=item.get("title"), preambule=item.get("preambule"), body=item.get("body"))


def reverse_func(apps, schema_editor):
    # Get model
    News = apps.get_model("mainapp", "News")
    # Delete objects
    News.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
