# Generated by Django 3.2.16 on 2023-01-27 04:41
from json import load

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    with open("mainapp/fixtures/002_courses.json") as f:
        courses_fixture = load(f)
    Courses = apps.get_model("mainapp", "Courses")
    # Create model's objects
    for item in courses_fixture:
        if not Courses.objects.filter(
            name=item.get("name"), description=item.get("description"), cost=item.get("cost")
        ).exists():
            if item.get("name") and item.get("description") and item.get("cost"):
                Courses.objects.create(title=item.get("name"), preambule=item.get("description"), body=item.get("cost"))


def reverse_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Delete objects
    Courses.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_news_model_data_migration"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
