# Generated by Django 3.2.16 on 2023-01-27 04:42

from json import load

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    with open("mainapp/fixtures/003_lessons.json") as f:
        lessons_fixture = load(f)
    Lesson = apps.get_model("mainapp", "Lesson")
    Courses = apps.get_model("mainapp", "Courses")
    # Create model's objects
    for item in lessons_fixture:
        if not Lesson.objects.filter(
            num=item.get("num"), title=item.get("title"), description=item.get("description")
        ).exists():
            if (
                item.get("num")
                and item.get("title")
                and item.get("description")
                and Courses.objects.filter(pk=item.get("courses")).exsist()
            ):
                Lesson.objects.create(
                    num=item.get("num"),
                    title=item.get("title"),
                    description=item.get("description"),
                    courses=Courses.objects.get(pk=item.get("courses")),
                )


def reverse_func(apps, schema_editor):
    # Get model
    Courses = apps.get_model("mainapp", "Courses")
    # Delete objects
    Courses.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_courses_model_data_migration"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
