# Generated by Django 3.2.16 on 2023-01-27 04:43

from json import load

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Get model
    with open("mainapp/fixtures/004_teachers.json") as f:
        teachers_fixture = load(f)
    CourseTeachers = apps.get_model("mainapp", "CourseTeachers")
    Courses = apps.get_model("mainapp", "Courses")
    # Create model's objects
    for item in teachers_fixture:
        if not CourseTeachers.objects.filter(
            name_first=item.get("name_first"),
            name_second=item.get("name_second"),
            day_birth=item.get("day_birth"),
            courses=item.get("courses"),
        ).exists():
            if item.get("name_first") and item.get("name_second") and item.get("day_birth"):
                courses_objs = [Courses.objects.get(pk=pk) for pk in item.get("courses")]
                CourseTeachers.objects.create(
                    name_first=item.get("name_first"),
                    name_second=item.get("name_second"),
                    day_birth=item.get("day_birth"),
                    courses=courses_objs,
                )


def reverse_func(apps, schema_editor):
    # Get model
    CourseTeachers = apps.get_model("mainapp", "CourseTeachers")
    # Delete objects
    CourseTeachers.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_lessons_model_data_migration"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
